### PR TITLE
fix - decode: extract length

### PR DESCRIPTION
**Pull request by ilteoood**
For the same reason I've opened the other PR, I would like to speed up performances of the decode function by extracting the length of the string.

### CODE REVIEW

**Comment by WebReflection** [comment]
This doesn’t improve perf much if at all (the string is not mutated, its length access is constant, but it performs worse with gzip or brotli … it was already like that and I’ve reverted as it’s not the bottleneck at all here and it produces a slightly bigger outcome.

if you have any benchmark that shows how faster this is though, I’m curious …

**Comment by ilteoood** [comment]
Not explicitly related to this scenario, but extracting the length in a const is always faster than accessing it through an object:

**Comment by WebReflection** [comment]
@ilteoood yes ... we're talking about `0.00x` difference, which is why I think it's premature optimization. The bottleneck here is not the loop per-se, rather the need for such loop due lack of base64 primitives and because we gain nothing relevant but it compresses worse I am not sure I want that in here. I do usually extract the length but here is all about compressing ... this code shouldn't bother you, it's the idea behind that should excite instead.

**edit** as a side note, you can just use the `for` loop declaration to get that length as `const` VS `let` doesn't change anything in terms of performance there.

**Comment by WebReflection** [comment]
I took the opportunity to declare everything once, use memoized `length` and also introduce the fastest way to `decode` via the extra `stream` method which is 2x to 3x faster than before (the real bottleneck).

I've also removed the need to create `new Response` which was silly from my side.

Related MR https://github.com/WebReflection/buffer-to-base64/commit/fc780f8a8985577726dd9ff3f18a2bcc98390445

**Pull request closed without merging**
